### ISSUE TITLE
Upoload command not implemented?

### ISSUE THREAD

**Issue by vladiks** [pavelrevak/pystlink#2]
I tried to upload short program to SRAM by using `upload` command like this:

`python3 pystlink.py upload:bytesWrite.srec`

but it gives me error

`*** Bad param "upload:bytesWrite.srec" ***`

When I look into the pystlink.py, it looks like upload command is not implemented in `cmd` method...?

**Comment by pavelrevak** [comment]
Use `write` command, I forget change README.. (more accurate info is in --help)

**Comment by vladiks** [comment]
Everything working now. Thanks for quick advice and great tool.
