### ISSUE TITLE
flash:erase:verify:address:bin will raise *** Parameter error: 16384 *** when writing bin file to address which already contain data

### ISSUE THREAD

**Issue by jxltom** [pavelrevak/pystlink#7]
```flash:erase:verify:address:bin``` will raise ```*** Parameter error: 16384 ***``` when writing bin file to address which already contain data

But if I using ```flash:verify:address:bin``` without erasing it, ```Verify error at block address``` will raise...

**Comment by pavelrevak** [comment]
and address is `0x4000`?

**Comment by jxltom** [comment]
@pavelrevak I am using STM32F407, the address is 0x0800ec10. I am trying to write 13bytes size data and this error raised.

By the way, if the address is only \xff data, everything is fine.
